version: '3'
services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: "exit 0"

  userService:
    image: ragour0001/userserviceimage:v1
    restart: always
    network_mode: host
    depends_on:
      - mysql
      - eurekaServer
      - rabbitmq
    ports:
      - 8071:8071
    healthcheck:
      test: "exit 0"

  favouriteService:
    image: ragour0001/favouriteserviceimage:v1
    restart: always
    network_mode: host
    depends_on:
      - mongo
      - eurekaServer
      - rabbitmq
    ports:
      - 8072:8072
    healthcheck:
      test: "exit 0"

  articleRecommService:
    image: ragour0001/articlerecommendationserviceimage:v1
    restart: always
    network_mode: host
    depends_on:
      - mongo
      - eurekaServer
      - rabbitmq
    ports:
      - 8074:8074
    healthcheck:
      test: "exit 0"

  eurekaServer:
    image: ragour0001/eurekaserviceimage:v1
    restart: always
    network_mode: host
    ports:
      - 9004:9004
    healthcheck:
      test: "exit 0"

  zuulService:
    image: ragour0001/zuulserviceimage:v1
    restart: always
    network_mode: host
    ports:
      - 8073:8073
    healthcheck:
      test: "exit 0"

  mysql:
    image: mysql:5.5
    ports:
     - 3306:3306
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: UserNewsAppDb
      MYSQL_USER: approot
      MYSQL_PASSWORD: root123
    healthcheck:
      test: "exit 0"

  angular:
    image: ragour0001/frontendimage:v3
    network_mode: host
    container_name: angular-docker
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"

  mongo:
    image: mongo:3.2-jessie
    ports:
     - 27017:27017
    container_name: mongo
    network_mode: host
    healthcheck:
      test: "exit 0"


